name: approx CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache Scala
      uses: coursier/cache-action@v6
    - name: Setup Scala
      uses: coursier/setup-action@v1
      with:
        jvm: adopt:11
        apps: sbt
    - name: Setup Dependencies
      run: sudo apt-get install verilator
    - name: Run tests
      run: sbt test
